### ISSUE TITLE
string index out of range

### ISSUE THREAD

**Issue by LiebeVerletzt** [dpm12345/nonebot_plugin_tts_gal#19]
好像是溢出错误，但不懂代码不知道怎么修；改用sample后加载了一次模型，但好像是找不到什么文件生成失败（有回复），重启后也一起报这个错了（未加载模型所以无回复）。

最后两句为：……
 File "C:\……\text\cleaners.py", line 156, in japanese_cleaners
    if re.match('[A-Za-z]', text[-1]):
IndexError: string index out of range

全报错如下：
12-06 17:31:19 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_tts_gal) failed.
Traceback (most recent call last):
  File "C:\Users\Administrator.DESKTOP-B93KCBS\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator.DESKTOP-B93KCBS\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator.DESKTOP-B93KCBS\AppData\Local\Programs\Python\Python310\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\Administrator.DESKTOP-B93KCBS\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator.DESKTOP-B93KCBS\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator.DESKTOP-B93KCBS\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Administrator.DESKTOP-B93KCBS\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator.DESKTOP-B93KCBS\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Administrator.DESKTOP-B93KCBS\AppData\Local\Programs\Python\Python310\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\Users\Administrator.DESKTOP-B93KCBS\AppData\Local\Programs\Python\Python310\lib\site-packages\nb_cli\handlers\deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "C:\Users\Administrator.DESKTOP-B93KCBS\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator.DESKTOP-B93KCBS\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "C:\Users\Administrator.DESKTOP-B93KCBS\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\Users\Administrator.DESKTOP-B93KCBS\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator.DESKTOP-B93KCBS\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator.DESKTOP-B93KCBS\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator.DESKTOP-B93KCBS\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator.DESKTOP-B93KCBS\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\Administrator.DESKTOP-B93KCBS\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\Administrator.DESKTOP-B93KCBS\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator.DESKTOP-B93KCBS\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\Administrator.DESKTOP-B93KCBS\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator.DESKTOP-B93KCBS\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator.DESKTOP-B93KCBS\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 702, in simple_run
    await handler(
  File "C:\Users\Administrator.DESKTOP-B93KCBS\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Administrator.DESKTOP-B93KCBS\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_tts_gal\__init__.py", line 87, in voicHandler
    text = get_text(text, hps_ms, symbols, lang, False)
  File "C:\Users\Administrator.DESKTOP-B93KCBS\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_tts_gal\function.py", line 58, in get_text
    text_norm = text_to_sequence(
  File "C:\Users\Administrator.DESKTOP-B93KCBS\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_tts_gal\text\__init__.py", line 17, in text_to_sequence
    clean_text = _clean_text(text, cleaner_names)
  File "C:\Users\Administrator.DESKTOP-B93KCBS\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_tts_gal\text\__init__.py", line 32, in _clean_text
    text = cleaner(text)
  File "C:\Users\Administrator.DESKTOP-B93KCBS\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_tts_gal\text\cleaners.py", line 156, in japanese_cleaners
    if re.match('[A-Za-z]', text[-1]):
IndexError: string index out of range

**Comment by dpm12345** [comment]
看着好像是文本内容没接收到，可以提供一下gocq的截图吗

**Comment by LiebeVerletzt** [comment]
gocq还挂着其他插件 回复正常 我重新添加一下启动列表

**Comment by LiebeVerletzt** [comment]
这个是![image](https://user-images.githubusercontent.com/76628910/205880124-2e5d79eb-3ed9-42e3-a724-b81b30f5f70e.png)

**Comment by dpm12345** [comment]
> 这个是![image](https://user-images.githubusercontent.com/76628910/205880124-2e5d79eb-3ed9-42e3-a724-b81b30f5f70e.png)

这个应该是模型配置文件的`symbols`项与模型不匹配，你可以找找原作者训练用的`symbols`

**Comment by LiebeVerletzt** [comment]
好的 打扰了 好像和上一个人问的问题一样
我们都是用的pjsk模型 但是报错不同 所以过来问了一下

**Comment by LiebeVerletzt** [comment]
不太行，用默认模型也会出现类似的报错。如果是symbols不匹配的话应该会回复错误文本才对，这个问题发生在加载模型之前，只有小概率能进入加载模型
![image](https://user-images.githubusercontent.com/76628910/205904971-b0a0ccaf-efb8-4933-9d6a-65993a4e8196.png)

**Comment by dpm12345** [comment]
我认为是接受到的消息文本的问题，截一下gocq端的图

**Comment by LiebeVerletzt** [comment]
![image](https://user-images.githubusercontent.com/76628910/205907554-335fce49-259d-4933-9482-0735e5808072.png)

**Comment by dpm12345** [comment]
我这边也看不出来是什么问题了
你可以前后测试一下文本信息是否成功被接收到了
或者再重装试试
插件本身应该是没有问题的

**Comment by LiebeVerletzt** [comment]
确实有成功收到，并且无论哪个模型哪个文本报错都是一模一样的，插件和环境都重装过了
虽然很遗憾但是只能接受了，计划自己研究一下怎么将https://github.com/Kanade-nya/PJSK-MultiGUI这个项目能用bot发出来吧
为我浪费这么多时间 很感谢

**Comment by LiebeVerletzt** [comment]
发现问题所在了，只要我开着代理，即使cqhttp端收到了消息，插件也读取不到，非常神秘……
而我测试的时候多半是开着代理浏览github的，所以才一会儿好使一会儿不好使
