### ISSUE TITLE
Running matcher <Matcher from nonebot_plugin_tts_gal, type=message, priority=3, temp=False> failed.

### ISSUE THREAD

**Issue by TsubakiAwa** [dpm12345/nonebot_plugin_tts_gal#25]
12-12 17:22:51 [SUCCESS] nonebot | NoneBot is initializing...
12-12 17:22:51 [INFO] nonebot | Current Env: prod
12-12 17:22:51 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_guild_patch"
12-12 17:22:51 [SUCCESS] nonebot | Succeeded to import "ping"
Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\SOLARV~1\AppData\Local\Temp\jieba.cache
Loading model cost 0.558 seconds.
Prefix dict has been built successfully.
12-12 17:22:55 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_tts_gal"
12-12 17:22:55 [SUCCESS] nonebot | Running NoneBot...
12-12 17:22:55 [INFO] uvicorn | Started server process [12292]
12-12 17:22:55 [INFO] uvicorn | Waiting for application startup.
12-12 17:22:55 [INFO] nonebot_plugin_tts_gal | 正在检查目录是否存在...
12-12 17:22:55 [INFO] nonebot_plugin_tts_gal | 正在检查配置文件是否存在...
12-12 17:22:55 [INFO] nonebot_plugin_tts_gal | 正在检查配置项...
12-12 17:22:55 [INFO] uvicorn | Application startup complete.
12-12 17:22:55 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:8181 (Press CTRL+C to quit)
12-12 17:22:57 [INFO] uvicorn | ('127.0.0.1', 63863) - "WebSocket /onebot/v11/ws" [accepted]
12-12 17:22:57 [INFO] nonebot | OneBot V11 | Bot 2 connected
12-12 17:22:57 [INFO] websockets | connection open
12-12 17:25:39 [SUCCESS] nonebot | ONEBOT V11 2 | [message.private.friend]: Message -1 from 1"宁宁说こんにちは"
12-12 17:25:39 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_tts_gal, type=message, priority=3, temp=False>
12-12 17:25:39 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_tts_gal, type=message, priority=3, temp=False> running complete
12-12 17:25:39 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_tts_gal, type=message, priority=3, temp=False> failed.
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\software\NoneBot2\venv\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "D:\software\NoneBot2\venv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\software\NoneBot2\venv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\software\NoneBot2\venv\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\software\NoneBot2\venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\software\NoneBot2\venv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\software\NoneBot2\venv\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "D:\software\NoneBot2\venv\lib\site-packages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "D:\software\NoneBot2\venv\lib\site-packages\nonebot\__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "D:\software\NoneBot2\venv\lib\site-packages\nonebot\drivers\fastapi.py", line 170, in run
    uvicorn.run(
  File "D:\software\NoneBot2\venv\lib\site-packages\uvicorn\main.py", line 576, in run
    server.run()
  File "D:\software\NoneBot2\venv\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Program Files\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 1899, in _run_once
    handle._run()
  File "C:\Program Files\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\software\NoneBot2\venv\lib\site-packages\nonebot\message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "D:\software\NoneBot2\venv\lib\site-packages\nonebot\message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\software\NoneBot2\venv\lib\site-packages\nonebot\internal\matcher.py", line 672, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\software\NoneBot2\venv\lib\site-packages\nonebot\internal\matcher.py", line 639, in simple_run
    await handler(
  File "D:\software\NoneBot2\venv\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
  File "D:\software\NoneBot2\venv\lib\site-packages\nonebot_plugin_tts_gal\__init__.py", line 80, in voicHandler
    hps_ms = get_hparams_from_file(config_path / config_file)
  File "D:\software\NoneBot2\venv\lib\site-packages\nonebot_plugin_tts_gal\utils.py", line 66, in get_hparams_from_file
    config = loads(data)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python310\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 35 column 4 (char 1226)

![image](https://user-images.githubusercontent.com/53134066/207011263-d2c6a759-6f34-4541-9782-4fb945b88c44.png)
![image](https://user-images.githubusercontent.com/53134066/207011944-e3f47dd8-e7fb-4c66-804c-54e205617986.png)

**Comment by dpm12345** [comment]
`YuzuSoft.json`文件格式错误了吧

**Comment by TsubakiAwa** [comment]
草，还真是，我错误理解了这个选项了[修改模型配置文件](https://github.com/dpm12345/nonebot_plugin_tts_gal/blob/master/Usage.md#%E4%BF%AE%E6%94%B9%E6%A8%A1%E5%9E%8B%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6)

**Comment by TsubakiAwa** [comment]
![image](https://user-images.githubusercontent.com/53134066/207182495-8a564d29-6fbb-4d95-aa95-fceafabed4c0.png)
但是我把  "language": "ja"掉后提示了这个
![image](https://user-images.githubusercontent.com/53134066/207182659-7c1f8a5f-4e3f-472a-b32f-192f89b8cef2.png)

**Comment by TsubakiAwa** [comment]
[YuzuSoft.json](https://github.com/dpm12345/nonebot_plugin_tts_gal/blob/master/data/nonebot_plugin_tts_gal/config/YuzuSoft.json)参考这个解决了
